config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  get '/about', to: 'homes#about'
  get '/contact', to: 'homes#contact'
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :contact])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
  end
  
  def show
    if current_user.present?
      @event = Event.find(params[:id])
    else
      render :error, status: :unprocessable_entity
    end
  end

  def new
    # if current_user.present?
     @event = Event.new
   # else
    # render :error, status: :unprocessable_entity
  # end
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def event_params
      params.require(:event).permit(:name, :description, :venue, :event_type, :start_date, :end_time, :total_duration, :is_paid
)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:name, :contact)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div class="form-group m-1 p-1 col">
    <%= form.label :name, class: "form-label" %><br>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :venue, class: "form-label" %><br>
    <%= form.select( :venue, options_for_select(['convention center', 'confrence hall', 'hotel', 'restaurants', 'resort', 'Breweries and wineries', 'Bars and nightclubs', 'Golf courses', 'Social clubs and lounges', 'Community centers', 'Museums, aquariums, and zoos', 'Art galleries', 'Historical and cultural estates', 'Theaters', ' Colleges and universities', 'Retreat centers', 'Cruise ships', 'Stadiums', 'other']),{} , class: "form-select")%>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :event_type, class: "form-label" %><br>
    <%= form.select( :event_type, options_for_select(['Corporate off-sites & executive meetings', 'seminars', 'confrences', 'trade shows', 'Company parties', 'product launch', 'birthday', 'marriage', 'get together', 'reception', 'other']),{} , class: "form-select")%>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :start_date, class: "form-label" %><br>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :end_time, class: "form-label"  %><br>
    <%= form.date_field :end_time, class: "form-control"  %>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :total_duration, class: "form-label"  %><br>
    <%= form.time_field :total_duration, class: "form-control" %>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :description, class: "form-label" %><br>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group m-1 p-1 col">
    <%= form.label :is_paid %><br>
    <div class="input-group mb-3">
      <div class="input-group-text">
        <input class="form-check-input mt-0" type="checkbox" value=":is_paid" aria-label="Checkbox for   following text input">
      </div>
      <input type="text" class="form-control" aria-label="Text input with checkbox">
    </div>
  </div>


  <div class="form-group m-1 p-1 col">
    <%#= form.submit %>
    <button type="submit" class="btn btn-secondary btn-lg">Submit</button>
    <div class="btn btn-secondary btn-lg"><%= link_to "Back", :back %></div>
  </div><br><br>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/error.html.erb
<div class="text-center"><h1>User not logged in</h1>
<p>First log in user</p>
<button><%= link_to 'back', :back %></button>
</div>

app/views/events/index.html.erb
<h1>Events</h1>
<div class="container">
  <div class="row">
    <% @events.each do |e| %>
      <div class="card mb-3 col-5 m-4" style="max-width: 540px;">
        <div class="row g-0">
          
          <div class="col-md-4">
            <img src=<%= asset_path("im.jpg") %> class="img-fluid rounded-start" alt="Events">
          </div>

          <div class="col-md-8">
            <div class="card-body">

              <h5 class="card-title">
                <%= link_to e.name, e %>
              </h5>

              <p class="card-text">
                <%= e.description%>
              </p>

              <p class="card-text">
                <small class="text-muted">Last updated at <%= e.updated_at %></small>
              </p>

            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>
<% if current_user.present? %>
<%= link_to "Create Event", new_event_path %>
<% end %>

app/views/events/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="card w-50 shadow p-3 mb-5 bg-body-tertiary rounded">
      <div class="form-group m-1 p-1 col">
      <h2>New Event</h2></div>

      <%= render "form", event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<h1>Name : <%= @event.name %></h1>

<p>Event Type : <%= @event.event_type %></p>
<p>Venue : <%= @event.venue %></p>
<p>Start date : <%= @event.start_date %></p>
<p>End date : <%= @event.end_time %></p>
<p>total duration : <%= @event.total_duration %></p>
<p>Description : <%= @event.description %></p>
<p>Event paid or not : <%= @event.is_paid %></p>


<ul>
  <li><%= link_to 'update info.', edit_event_path(@event) %></li>
  <li><%= link_to "Cancel Event", event_path(@event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to 'back', events_path %></li>
</ul>

app/views/homes/about.html.erb
<%= stylesheet_link_tag "style1"  %>
<div class="about">
  <!-- <div class="overlay"></div> -->
  <div class="container">
    <div class="row align-items-center z-3">
      <div class="col-6">
        <div class="about_content">
          <h2>About</h2>
            <p>
              Founded in 2006 with the goal of making knowledge sharing easy, Slideshare has since grown into a top destination for professional content. With over 18 million uploads in 40 content categories, it is today one of the top 100 most-visited websites in the world.
              top destination for professional content. With over 18 million uploads in 40 content categories, it is today one of the top 100 most-visited websites in the world.
            </p>
            <button class="btn btn-outline-light">Learn More</button>
        </div>
      </div>
      <div class="col-6" >
        <div class="about_img_section">          
          <div class="about_bg_white"></div>
            <img src="<%=asset_path('fireworks.gif')%>" alt="about" class=" about_img ">
          </div>
        </div>
      </div>
  </div>
  <button><%= link_to 'back', :back %></button>
</div>

app/views/homes/contact.html.erb
<!--Section: Contact v.2-->
<div class="container">
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row"> 

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0 mt-3">
                            <label for="name" class="m-2">Your name</label>
                            <input type="text" id="name" name="name" class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0 mt-3">
                            <label for="email" class="m-2">Your email</label>
                            <input type="text" id="email" name="email" class="form-control">
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0 mt-3">
                            <label for="subject" class="m-2">Subject</label>
                            <input type="text" id="subject" name="subject" class="form-control">
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form mt-3 ">
                            <label for="message" class="m-2">Your message</label>
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left mt-3">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center mt-5">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Indore, IND 94126, IND</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>eventindia.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
</div>
<!--Section: Contact v.2-->

app/views/homes/index.html.erb
<%= stylesheet_link_tag "style" %>
<h1>Here is Our Event's schedule</h1><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkashEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fsvs/1.2.2/js/bundle.min.js"></script>

    <%#= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%#= render "shared/khoofiya" %>
    <%#= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
 <footer class="text-center text-white fixed-bottom" style="background-color: black;">
  

  <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0);">
    <button class="btn btn-outline-success" type="submit">
    <%= link_to 'back', :back %></button>
    © 2023 Copyright :
    <a class="text-white" href="http://127.0.0.1:3000"> AkashEvent.com</a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Akash Event</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/about">About</a></li>
            <li><a class="dropdown-item" href="/contact">Contact us</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Link</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav> -->
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h4 class="text-white h4">Are wahh event plan kr <br>rahe ho sai h sai h niche padho</h4>
    <span class="text-white">bagal wala 3 lin button dikh ra h use thoko<br> ya fir niche di hui link pe click <br>krke action perform kro</span>
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Link
      </a>
      <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/about">About us</a></li>
            <li><a class="dropdown-item" href="/contact">Contact us</a></li>
            <li><a class="dropdown-item" href="/">Back to Home</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/events/index">Check all Events</a></li>
          </ul>
        </li>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/events">Akash Event</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/about">About us</a></li>
            <li><a class="dropdown-item" href="/contact">Contact us</a></li>
            <li><a class="dropdown-item" href="/users/sign_up">Sign up</a></li>
            <li><a class="dropdown-item" href="/users/sign_in">log in</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/">home</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link">Link</a>
        </li>
         <% if user_signed_in? %>
            <%= current_user.email %>
            <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>          <!-- <%#= button_to 'Sign Out', destroy_user_session_path, method: :delete,
              form: {data: {turbo_confirm: 'Are you sure?'}} %> -->
              <% else %>
            <li class="nav-item">
              <button class="btn btn-outline-success" type="submit">
              <%= link_to 'create user', new_user_registration_path %></button>
              <button class="btn btn-outline-success" type="submit">
              <%= link_to 'log in user', new_user_session_path %></button>
            </li>
            <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
show.html.erb